databases:
  - name: trading-strategy-db
    databaseName: trading_strategy
    user: trading_strategy_user

services:
  - type: web
    name: trading-strategy-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trading-strategy-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0